export type Tradition = 'siddha' | 'ayurveda' | 'natural';

export interface MedicineCategory {
  id: string;
  nameTa: string;
  nameEn: string;
  slug: string;
  icon: string;
  createdAt: string;
}

export interface SeedMedicine {
  id: string;
  slug: string;
  nameTa: string;
  nameEn: string;
  categoryId: string;
  categorySlug: string;
  categoryNameTa: string;
  categoryNameEn: string;
  tradition: Tradition;
  price: number;
  mrp: number;
  rating: number;
  reviewCount: number;
  stockCount: number;
  inStock: boolean;
  prescriptionRequired: boolean;
  imageUrl?: string;
  artTone: 'emerald' | 'teal' | 'gold' | 'cyan' | 'leaf' | 'coral';
  overview: string;
  ingredients: string;
  generalUses: string;
  safetyNotes: string;
  faqs: Array<{ question: string; answer: string }>;
  createdAt: string;
  updatedAt: string;
}

const now = new Date('2026-01-01T00:00:00.000Z').toISOString();

export const MEDICINE_CATEGORIES: MedicineCategory[] = [
  { id: 'cat_siddha', nameTa: 'சித்த மருத்துவம்', nameEn: 'Siddha', slug: 'siddha', icon: 'Leaf', createdAt: now },
  { id: 'cat_ayurveda', nameTa: 'ஆயுர்வேதம்', nameEn: 'Ayurveda', slug: 'ayurveda', icon: 'Sprout', createdAt: now },
  { id: 'cat_natural', nameTa: 'இயற்கை நலம்', nameEn: 'Natural wellness', slug: 'natural-wellness', icon: 'Flower', createdAt: now },
  { id: 'cat_digestive', nameTa: 'செரிமான பராமரிப்பு', nameEn: 'Digestive care', slug: 'digestive-care', icon: 'Apple', createdAt: now },
  { id: 'cat_skin', nameTa: 'தோல் பராமரிப்பு', nameEn: 'Skin care', slug: 'skin-care', icon: 'Sparkles', createdAt: now },
  { id: 'cat_hair', nameTa: 'முடி பராமரிப்பு', nameEn: 'Hair care', slug: 'hair-care', icon: 'Droplet', createdAt: now },
  { id: 'cat_immunity', nameTa: 'நோய் எதிர்ப்பு ஆதரவு', nameEn: 'Immunity support', slug: 'immunity-support', icon: 'Shield', createdAt: now },
  { id: 'cat_wellness', nameTa: 'பொது நலன்', nameEn: 'General wellness', slug: 'general-wellness', icon: 'HeartPulse', createdAt: now },
  { id: 'cat_pain', nameTa: 'வலி நிவாரணம்', nameEn: 'Pain relief', slug: 'pain-relief', icon: 'Activity', createdAt: now },
  { id: 'cat_fever', nameTa: 'காய்ச்சல் பராமரிப்பு', nameEn: 'Fever care', slug: 'fever-care', icon: 'Thermometer', createdAt: now },
];

const categoryBySlug = new Map(MEDICINE_CATEGORIES.map((category) => [category.slug, category]));

function medicine(
  index: number,
  input: Omit<SeedMedicine, 'id' | 'categoryId' | 'categoryNameTa' | 'categoryNameEn' | 'createdAt' | 'updatedAt' | 'faqs'> & {
    faqs?: SeedMedicine['faqs'];
  },
): SeedMedicine {
  const category = categoryBySlug.get(input.categorySlug);
  if (!category) throw new Error(`Unknown category ${input.categorySlug}`);

  return {
    ...input,
    id: `prod_${String(index).padStart(3, '0')}`,
    categoryId: category.id,
    categoryNameTa: category.nameTa,
    categoryNameEn: category.nameEn,
    createdAt: new Date(new Date(now).getTime() + index * 86400000).toISOString(),
    updatedAt: new Date(new Date(now).getTime() + index * 86400000).toISOString(),
    faqs: input.faqs ?? [
      {
        question: 'Can I use this without advice?',
        answer: 'This page is educational only. Please consult a qualified doctor or pharmacist before use.',
      },
      {
        question: 'Does Vaithiyam provide dosage guidance?',
        answer: 'No. Vaithiyam does not provide diagnosis, dosage, or self-medication recommendations.',
      },
    ],
  };
}

export const SEED_PRODUCTS: SeedMedicine[] = [
  medicine(1, {
    slug: 'triphala-churnam',
    nameTa: 'திரிபல சூரணம்',
    nameEn: 'Triphala Churnam',
    categorySlug: 'digestive-care',
    tradition: 'ayurveda',
    price: 180,
    mrp: 220,
    rating: 4.7,
    reviewCount: 312,
    stockCount: 45,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'gold',
    overview: 'A traditional herbal powder format listed for educational awareness in digestive wellness categories.',
    ingredients: 'Herbal composition commonly associated with amla, haritaki, and bibhitaki.',
    generalUses: 'General wellness and digestive-care education. This is not a treatment recommendation.',
    safetyNotes: 'Consult a doctor or pharmacist before use, especially during pregnancy, lactation, chronic illness, or ongoing medication.',
  }),
  medicine(2, {
    slug: 'neem-leaf-powder',
    nameTa: 'வேப்பிலை சூரணம்',
    nameEn: 'Neem Leaf Powder',
    categorySlug: 'skin-care',
    tradition: 'siddha',
    price: 120,
    mrp: 150,
    rating: 4.5,
    reviewCount: 198,
    stockCount: 28,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'leaf',
    overview: 'A neem-based herbal product for educational catalogue browsing in natural care.',
    ingredients: 'Neem leaf powder and plant-based excipients where applicable.',
    generalUses: 'General skin-care and wellness education only.',
    safetyNotes: 'Avoid self-medication. Ask a qualified practitioner if you have allergies or sensitive skin.',
  }),
  medicine(3, {
    slug: 'amalaki-churnam',
    nameTa: 'ஆமலகி சூரணம்',
    nameEn: 'Amalaki Churnam',
    categorySlug: 'immunity-support',
    tradition: 'ayurveda',
    price: 210,
    mrp: 260,
    rating: 4.8,
    reviewCount: 445,
    stockCount: 0,
    inStock: false,
    prescriptionRequired: false,
    imageUrl: '/prod-harmony.png',
    artTone: 'cyan',
    overview: 'Amla-based traditional preparation displayed for safe product education.',
    ingredients: 'Amla fruit powder and plant-based processing aids where applicable.',
    generalUses: 'General wellness and immunity-support education. Not a disease claim.',
    safetyNotes: 'Consult a doctor or pharmacist before use if you have acidity, diabetes, or ongoing medication.',
  }),
  medicine(4, {
    slug: 'ashwagandha-churnam',
    nameTa: 'அஸ்வகந்தா சூரணம்',
    nameEn: 'Ashwagandha Churnam',
    categorySlug: 'general-wellness',
    tradition: 'ayurveda',
    price: 350,
    mrp: 420,
    rating: 4.9,
    reviewCount: 623,
    stockCount: 15,
    inStock: true,
    prescriptionRequired: true,
    imageUrl: '/prod-restoration.png',
    artTone: 'emerald',
    overview: 'A traditional herb product shown with prescription verification because professional suitability checks may be needed.',
    ingredients: 'Ashwagandha root powder and approved excipients where applicable.',
    generalUses: 'General traditional wellness education only. No dosage or self-medication advice is provided.',
    safetyNotes: 'Prescription verification is required before order confirmation. Consult a qualified doctor or pharmacist.',
  }),
  medicine(5, {
    slug: 'turmeric-capsules',
    nameTa: 'மஞ்சள் காப்சூல்',
    nameEn: 'Turmeric Capsules',
    categorySlug: 'natural-wellness',
    tradition: 'natural',
    price: 290,
    mrp: 340,
    rating: 4.6,
    reviewCount: 289,
    stockCount: 60,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'gold',
    overview: 'Turmeric wellness capsules listed for ingredient and product education.',
    ingredients: 'Turmeric extract or powder and capsule shell ingredients where applicable.',
    generalUses: 'General natural wellness education only.',
    safetyNotes: 'Ask a doctor or pharmacist before use if you take blood thinners or have gallbladder conditions.',
  }),
  medicine(6, {
    slug: 'brahmi-oil',
    nameTa: 'பிரம்மி எண்ணெய்',
    nameEn: 'Brahmi Hair Oil',
    categorySlug: 'hair-care',
    tradition: 'siddha',
    price: 195,
    mrp: 240,
    rating: 4.4,
    reviewCount: 167,
    stockCount: 33,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'teal',
    overview: 'A traditional hair oil product for catalogue browsing and ingredient education.',
    ingredients: 'Brahmi extract in herbal oil base and aromatic herbs where applicable.',
    generalUses: 'Hair-care education and routine wellness context only.',
    safetyNotes: 'Patch test externally and consult a pharmacist for irritation, allergy, or scalp conditions.',
  }),
  medicine(7, {
    slug: 'nilavembu-kudineer',
    nameTa: 'நிலவேம்பு குடிநீர்',
    nameEn: 'Nilavembu Kudineer',
    categorySlug: 'fever-care',
    tradition: 'siddha',
    price: 165,
    mrp: 210,
    rating: 4.6,
    reviewCount: 534,
    stockCount: 21,
    inStock: true,
    prescriptionRequired: true,
    artTone: 'leaf',
    overview: 'A Siddha classical preparation listed for educational awareness with prescription verification.',
    ingredients: 'Traditional herbal composition associated with nilavembu and companion herbs.',
    generalUses: 'Fever-care category education only. Vaithiyam does not diagnose fever or recommend treatment.',
    safetyNotes: 'Prescription verification is required. Seek medical care for fever or worsening symptoms.',
  }),
  medicine(8, {
    slug: 'kabazura-kudineer',
    nameTa: 'கபசுர குடிநீர்',
    nameEn: 'Kabasura Kudineer',
    categorySlug: 'immunity-support',
    tradition: 'siddha',
    price: 175,
    mrp: 225,
    rating: 4.5,
    reviewCount: 408,
    stockCount: 19,
    inStock: true,
    prescriptionRequired: true,
    artTone: 'coral',
    overview: 'A traditional Siddha preparation shown for educational catalogue purposes.',
    ingredients: 'Traditional multi-herb composition used in Siddha literature.',
    generalUses: 'General traditional wellness education only. No disease-prevention claim is made.',
    safetyNotes: 'Prescription verification is required. Consult a qualified practitioner before use.',
  }),
  medicine(9, {
    slug: 'sukku-malli-coffee',
    nameTa: 'சுக்கு மல்லி காபி',
    nameEn: 'Sukku Malli Coffee',
    categorySlug: 'general-wellness',
    tradition: 'siddha',
    price: 145,
    mrp: 180,
    rating: 4.3,
    reviewCount: 156,
    stockCount: 52,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'gold',
    overview: 'A traditional beverage mix catalogued as a comfort and wellness product.',
    ingredients: 'Dry ginger, coriander, and spice blend depending on batch.',
    generalUses: 'General wellness beverage education only.',
    safetyNotes: 'Consult a doctor if you have acidity, ulcers, pregnancy-related concerns, or medication interactions.',
  }),
  medicine(10, {
    slug: 'thoothuvalai-powder',
    nameTa: 'தூதுவளை சூரணம்',
    nameEn: 'Thoothuvalai Powder',
    categorySlug: 'natural-wellness',
    tradition: 'siddha',
    price: 135,
    mrp: 170,
    rating: 4.2,
    reviewCount: 119,
    stockCount: 31,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'emerald',
    overview: 'A traditional leaf powder listed for safe educational browsing.',
    ingredients: 'Thoothuvalai leaf powder and plant-based processing aids where applicable.',
    generalUses: 'General traditional wellness education only.',
    safetyNotes: 'Do not use as a substitute for medical care. Consult a professional before use.',
  }),
  medicine(11, {
    slug: 'vellai-kungiliyam-balm',
    nameTa: 'வெள்ளை குங்கிலியம் பால்ம்',
    nameEn: 'Herbal Comfort Balm',
    categorySlug: 'pain-relief',
    tradition: 'siddha',
    price: 95,
    mrp: 125,
    rating: 4.1,
    reviewCount: 86,
    stockCount: 44,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'cyan',
    overview: 'An external-use herbal balm listed for product education.',
    ingredients: 'Herbal oil base, resins, waxes, and aromatic ingredients where applicable.',
    generalUses: 'External comfort-care education only. Not a treatment recommendation.',
    safetyNotes: 'External use only. Avoid eyes, wounds, and irritated skin. Consult a pharmacist if symptoms persist.',
  }),
  medicine(12, {
    slug: 'moringa-tablets',
    nameTa: 'முருங்கை மாத்திரை',
    nameEn: 'Moringa Tablets',
    categorySlug: 'natural-wellness',
    tradition: 'natural',
    price: 240,
    mrp: 290,
    rating: 4.4,
    reviewCount: 203,
    stockCount: 47,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'leaf',
    overview: 'Moringa-based tablets shown for nutrition and ingredient education.',
    ingredients: 'Moringa leaf powder and approved excipients where applicable.',
    generalUses: 'General nutrition support education only.',
    safetyNotes: 'Ask a doctor or pharmacist before use if pregnant, lactating, diabetic, or taking medication.',
  }),
  medicine(13, {
    slug: 'aloe-vera-gel',
    nameTa: 'கற்றாழை ஜெல்',
    nameEn: 'Aloe Vera Gel',
    categorySlug: 'skin-care',
    tradition: 'natural',
    price: 160,
    mrp: 210,
    rating: 4.5,
    reviewCount: 248,
    stockCount: 40,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'teal',
    overview: 'Aloe-based topical product listed for skin-care education.',
    ingredients: 'Aloe vera gel base with stabilizers and approved preservatives where applicable.',
    generalUses: 'General topical skin-care education only.',
    safetyNotes: 'Patch test first. Stop use and consult a professional if irritation occurs.',
  }),
  medicine(14, {
    slug: 'vetiver-soap',
    nameTa: 'வெட்டிவேர் சோப்பு',
    nameEn: 'Vetiver Herbal Soap',
    categorySlug: 'skin-care',
    tradition: 'natural',
    price: 85,
    mrp: 110,
    rating: 4.0,
    reviewCount: 74,
    stockCount: 64,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'gold',
    overview: 'A herbal soap product with vetiver-inspired fragrance and ingredient education.',
    ingredients: 'Soap base, vetiver fragrance, and plant-derived additives where applicable.',
    generalUses: 'Personal-care education only.',
    safetyNotes: 'External use only. Avoid use on broken skin and discontinue if irritation occurs.',
  }),
  medicine(15, {
    slug: 'karisalankanni-hair-powder',
    nameTa: 'கரிசலாங்கண்ணி பொடி',
    nameEn: 'Karisalankanni Hair Powder',
    categorySlug: 'hair-care',
    tradition: 'siddha',
    price: 150,
    mrp: 195,
    rating: 4.2,
    reviewCount: 97,
    stockCount: 22,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'emerald',
    overview: 'A traditional hair-care powder listed for ingredient awareness.',
    ingredients: 'Karisalankanni leaf powder and companion herbs where applicable.',
    generalUses: 'Hair-care education only.',
    safetyNotes: 'Patch test. Consult a dermatologist or pharmacist for scalp conditions.',
  }),
  medicine(16, {
    slug: 'arugampul-powder',
    nameTa: 'அருகம்புல் பொடி',
    nameEn: 'Arugampul Powder',
    categorySlug: 'general-wellness',
    tradition: 'siddha',
    price: 130,
    mrp: 165,
    rating: 4.1,
    reviewCount: 88,
    stockCount: 26,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'leaf',
    overview: 'A grass-based traditional product listed for safe educational browsing.',
    ingredients: 'Arugampul powder and plant-based processing aids where applicable.',
    generalUses: 'General wellness education only.',
    safetyNotes: 'Consult a qualified practitioner before use, especially for chronic conditions.',
  }),
  medicine(17, {
    slug: 'avipattikar-churnam',
    nameTa: 'அவிபத்திகர சூரணம்',
    nameEn: 'Avipattikar Churnam',
    categorySlug: 'digestive-care',
    tradition: 'ayurveda',
    price: 190,
    mrp: 235,
    rating: 4.3,
    reviewCount: 132,
    stockCount: 18,
    inStock: true,
    prescriptionRequired: true,
    artTone: 'coral',
    overview: 'A classical Ayurvedic preparation shown with prescription verification for safe ordering.',
    ingredients: 'Traditional multi-herb composition as per product label.',
    generalUses: 'Digestive-care category education only. No dosage advice is provided.',
    safetyNotes: 'Prescription verification is required. Consult a doctor or pharmacist before use.',
  }),
  medicine(18, {
    slug: 'jeeraka-arishtam',
    nameTa: 'ஜீரக அரிஷ்டம்',
    nameEn: 'Jeeraka Arishtam',
    categorySlug: 'digestive-care',
    tradition: 'ayurveda',
    price: 260,
    mrp: 320,
    rating: 4.4,
    reviewCount: 164,
    stockCount: 12,
    inStock: true,
    prescriptionRequired: true,
    artTone: 'gold',
    overview: 'A traditional liquid preparation listed with prescription verification.',
    ingredients: 'Cumin-based classical composition according to product label.',
    generalUses: 'Traditional digestive-care education only.',
    safetyNotes: 'Prescription verification is required. Avoid self-medication and seek professional guidance.',
  }),
  medicine(19, {
    slug: 'tulsi-drops',
    nameTa: 'துளசி டிராப்ஸ்',
    nameEn: 'Tulsi Drops',
    categorySlug: 'immunity-support',
    tradition: 'natural',
    price: 175,
    mrp: 220,
    rating: 4.3,
    reviewCount: 147,
    stockCount: 38,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'teal',
    overview: 'Tulsi extract product displayed for ingredient and general wellness education.',
    ingredients: 'Tulsi extract and approved carrier base where applicable.',
    generalUses: 'General wellness education only.',
    safetyNotes: 'Consult a doctor or pharmacist before use, especially with pregnancy or ongoing medication.',
  }),
  medicine(20, {
    slug: 'nannari-syrup',
    nameTa: 'நன்னாரி சர்பத்',
    nameEn: 'Nannari Syrup',
    categorySlug: 'general-wellness',
    tradition: 'siddha',
    price: 210,
    mrp: 260,
    rating: 4.2,
    reviewCount: 103,
    stockCount: 27,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'cyan',
    overview: 'A traditional syrup product listed for beverage and wellness education.',
    ingredients: 'Nannari root extract, sweetener base, and approved ingredients where applicable.',
    generalUses: 'General beverage wellness education only.',
    safetyNotes: 'Check sugar content and consult a doctor for diabetes or dietary restrictions.',
  }),
  medicine(21, {
    slug: 'herbal-steam-mix',
    nameTa: 'மூலிகை நீராவி மிக்ஸ்',
    nameEn: 'Herbal Steam Mix',
    categorySlug: 'general-wellness',
    tradition: 'natural',
    price: 115,
    mrp: 145,
    rating: 4.0,
    reviewCount: 67,
    stockCount: 36,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'emerald',
    overview: 'A herbal steam mix listed for comfort-care education.',
    ingredients: 'Eucalyptus-like aromatic herbs and plant material according to label.',
    generalUses: 'General comfort-care education only. Not a respiratory treatment recommendation.',
    safetyNotes: 'Avoid steam burns. Consult a doctor for breathing difficulty, fever, or persistent symptoms.',
  }),
  medicine(22, {
    slug: 'herbal-digestion-drops',
    nameTa: 'செரிமான ஹெர்பல் டிராப்ஸ்',
    nameEn: 'Herbal Digestion Drops',
    categorySlug: 'digestive-care',
    tradition: 'natural',
    price: 155,
    mrp: 190,
    rating: 4.1,
    reviewCount: 91,
    stockCount: 25,
    inStock: true,
    prescriptionRequired: false,
    artTone: 'teal',
    overview: 'A herbal drops product listed for ingredient awareness and safe browsing.',
    ingredients: 'Herbal extract blend and approved carrier base where applicable.',
    generalUses: 'Digestive-care education only. No dosage advice is provided.',
    safetyNotes: 'Consult a pharmacist before use if symptoms are severe, recurring, or medication-related.',
  }),
  medicine(23, {
    slug: 'pain-care-oil',
    nameTa: 'வலி பராமரிப்பு எண்ணெய்',
    nameEn: 'Pain Care Herbal Oil',
    categorySlug: 'pain-relief',
    tradition: 'siddha',
    price: 225,
    mrp: 280,
    rating: 4.4,
    reviewCount: 175,
    stockCount: 17,
    inStock: true,
    prescriptionRequired: true,
    artTone: 'coral',
    overview: 'An external-use traditional oil shown with prescription verification for safe ordering.',
    ingredients: 'Herbal oil base and traditional ingredient blend according to label.',
    generalUses: 'External comfort-care education only.',
    safetyNotes: 'Prescription verification is required. External use only; consult a practitioner for pain or injury.',
  }),
  medicine(24, {
    slug: 'daily-wellness-combo',
    nameTa: 'நித்திய ஆரோக்கியக் கலவை',
    nameEn: 'Daily Wellness Combo',
    categorySlug: 'general-wellness',
    tradition: 'natural',
    price: 499,
    mrp: 640,
    rating: 4.6,
    reviewCount: 221,
    stockCount: 14,
    inStock: true,
    prescriptionRequired: false,
    imageUrl: '/prod-combo.png',
    artTone: 'cyan',
    overview: 'A curated demo combo for browsing multiple wellness products in one card.',
    ingredients: 'Combination varies by included product label.',
    generalUses: 'General wellness catalogue education only.',
    safetyNotes: 'Review each product label and consult a qualified professional before use.',
  }),
  medicine(25, {
    slug: 'nithya-immunity-booster',
    nameTa: 'நித்திய நோய் எதிர்ப்பு பூஸ்டர்',
    nameEn: 'Nithya Immunity Booster',
    categorySlug: 'immunity-support',
    tradition: 'natural',
    price: 349,
    mrp: 450,
    rating: 4.8,
    reviewCount: 182,
    stockCount: 15,
    inStock: true,
    prescriptionRequired: false,
    imageUrl: '/prod-harmony.png',
    artTone: 'emerald',
    overview: 'A premium immunity support formulation with pure organic botanical extracts to enhance natural defense.',
    ingredients: 'Pure Giloy, Tulsi, Amla, and organic herbal extracts.',
    generalUses: 'Daily immunity enhancement, vitality, and wellness support.',
    safetyNotes: 'Consult a healthcare professional before use, especially if taking other medications.',
  }),
  medicine(26, {
    slug: 'mooligai-detox-mix',
    nameTa: 'மூலிகை நச்சு நீக்கி கலவை',
    nameEn: 'Mooligai Detox Mix',
    categorySlug: 'general-wellness',
    tradition: 'siddha',
    price: 299,
    mrp: 380,
    rating: 4.7,
    reviewCount: 143,
    stockCount: 22,
    inStock: true,
    prescriptionRequired: false,
    imageUrl: '/prod-restoration.png',
    artTone: 'teal',
    overview: 'An organic blend of seeds and traditional herbs to support natural cleansing and metabolic functions.',
    ingredients: 'Traditional herbal blend including Senna, Fennel, Cumin, and Turmeric.',
    generalUses: 'Natural body detoxification, digestion support, and gut health.',
    safetyNotes: 'Do not exceed the recommended usage. Review labels for allergies.',
  }),
  medicine(27, {
    slug: 'vajra-strength-powder',
    nameTa: 'வஜ்ரா வலிமை சூரணம்',
    nameEn: 'Vajra Strength Powder',
    categorySlug: 'general-wellness',
    tradition: 'ayurveda',
    price: 549,
    mrp: 680,
    rating: 4.9,
    reviewCount: 256,
    stockCount: 8,
    inStock: true,
    prescriptionRequired: false,
    imageUrl: '/prod-tonic.png',
    artTone: 'gold',
    overview: 'A robust strengthening powder containing traditional Ayurvedic herbs for stamina and physical strength.',
    ingredients: 'Pure Ashwagandha, Shatavari, Safed Musli, and Gokshura.',
    generalUses: 'Stamina enhancement, physical strength, vigor, and muscle rejuvenation.',
    safetyNotes: 'Consult an Ayurvedic practitioner before use if you have chronic health conditions.',
  }),
];

export function getMedicineInitials(nameEn: string) {
  return nameEn
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase())
    .join('');
}
